@startuml

left to right direction

actor Administrador
actor FuncionarioPublico
actor Promotor

rectangle SistemaGestionReconstruccion {
    (Crear Proyecto) as (CrearProyecto)
    (Aprobar Proyecto) as (AprobarProyecto)
    (Asignar Tareas) as (AsignarTareas)
    (Poner en Marcha Proyecto) as (PonerEnMarcha)
}

Administrador --> (CrearProyecto)
FuncionarioPublico --> (AprobarProyecto)
Promotor --> (AsignarTareas)
Promotor --> (PonerEnMarcha)

@enduml
